# Using trusty should yield newer compilers and packages
dist: trusty
language: cpp

compiler:
 - clang
 - gcc

install:
 - bash install-deps.sh

script:
    - ./premake5 gmake --include=wren-master/src/include --link=wren-master/lib
 - cd build/gmake
 - make all
